name: "Terminal on Fail"
description: "Get interactive terminal access to your GitHub Actions runner on failure"
author: "lawrencegripper"

inputs:
  server-url:
    description: "URL of the terminal server"
    required: true
  timeout:
    description: "How long to wait for connection (minutes)"
    required: false
    default: "30"
  otp-secret:
    description: "TOTP secret for terminal access (base32 encoded). Browser must provide valid OTP code before terminal access is granted."
    required: true

runs:
  using: "node20"
  main: "dist/main.js"
  post: "dist/post.js"
  post-if: failure()

branding:
  icon: "terminal"
  color: "green"
# Note: The workflow using this action must have:
# permissions:
#   id-token: write
